<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <PackageVersion>1.0.3</PackageVersion>
        <FileVersion>1.0.3</FileVersion>
        <Version>1.0.3</Version>
        <Authors>Denis Ivanov</Authors>
        <Description>NetTopologySuite (spatial) support for the DuckDB provider for Entity Framework Core.</Description>
        <PackageTags>DuckDB; Entity Framework Core; EF Core; NetTopologySuite; Spatial; GIS</PackageTags>
        <PackageIcon>DuckDB_icon-lightmode.png</PackageIcon>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/denis-ivanov/DuckDB.EFCore</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
      <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DuckDB.EFCore\DuckDB.EFCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\DuckDB_icon-lightmode.png" Pack="true" PackagePath="" />
      <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
      <None Include="..\..\README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
