<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageVersion>1.0.3</PackageVersion>
    <FileVersion>1.0.3</FileVersion>
    <Version>1.0.3</Version>
    <Nullable>enable</Nullable>
    <Authors>Denis Ivanov</Authors>
    <Description>DuckDB provider for Entity Framework Core.</Description>
    <PackageTags>DuckDB; Entity Framework Core; EF Core</PackageTags>
    <PackageIcon>DuckDB_icon-lightmode.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/denis-ivanov/DuckDB.EFCore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NoWarn>$(NoWarn);EF1001;EF9100</NoWarn>
    <IsPackable>true</IsPackable>
    <PackageReleaseNotes>
        Full Changelog: https://github.com/denis-ivanov/DuckDB.EFCore/compare/v1.0.2...v1.0.3
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\DuckDB_icon-lightmode.png" Pack="true" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
